class AppConstants {
  static const String mapKey = "AIzaSyAySvKWdZapIhaDQMB4GNskcVLWOI655Xw";
 // static const String mapApiKey = "AIzaSyCSlffgAvcUs3Y47F7xr4OqB88I84AD27k";
  static const String phoneRegExp = "^(00201|\\+201|01)[0-2,5]{1}[0-9]{8}\$";
  static const String termsUrl = "http://drop-eg.com/TermsofUse";
  static const String privacyUrl = "https://drop-eg.com/PrivacyPolicy";
 static const int  referralDiscount = 5;
 static const int  freeWashTotal = 5;
  static const List<String> cities = [
    "Cairo",
    "Giza",
    "Alexandria",
    "Dakahlia",
    "arRed Sea",
    "Beheira",
    "Fayoum",
    "Gharbiya",
    "Ismailia",
    "Menofia",
    "Minya",
    "Qaliubiya",
    "New Valley",
    "Suez",
    "Aswan",
    "Assiut",
    "Beni Suef",
    "Port Said",
    "Damietta",
    "Sharkia",
    "South Sinai",
    "Kafr Al sheikh",
    "Matrouh",
    "Luxor",
    "Qena",
    "North Sinai",
    "Sohag"
  ];

  static const List<String> manufacturer =[
    "Abarth",
    "Alfa Romeo",
    "Aston Martin",
    "Audi",
    "Bentley",
    "BMW",
    "Bugatti",
    "Cadillac",
    "Chevrolet",
    "Chrysler",
    "Citroën",
    "Dacia",
    "Daewoo",
    "Daihatsu",
    "Dodge",
    "Donkervoort",
    "DS",
    "Ferrari",
    "Fiat",
    "Fisker",
    "Ford",
    "Honda",
    "Hummer",
    "Hyundai",
    "Infiniti",
    "Iveco",
    "Jaguar",
    "Jeep",
    "Kia",
    "KTM",
    "Lada",
    "Lamborghini",
    "Lancia",
    "Land Rover",
    "Landwind",
    "Lexus",
    "Lotus",
    "Maserati",
    "Maybach",
    "Mazda",
    "McLaren",
    "Mercedes-Benz",
    "MG",
    "Mini",
    "Mitsubishi",
    "Morgan",
    "Nissan",
    "Opel",
    "Peugeot",
    "Porsche",
    "Renault",
    "Rolls-Royce",
    "Rover",
    "Saab",
    "Seat",
    "Skoda",
    "Smart",
    "SsangYong",
    "Subaru",
    "Suzuki",
    "Tesla",
    "Toyota",
    "Volkswagen",
    "Volvo"
  ];
}
